###Create Profile
POST localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Abdujalilov",
  "email": "ozod@gmail.ru2",
  "phone": "12344",
  "password": "2222",
  "status": "ACTIVE",
  "profileRole": "ROLE_USER"
}
####
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}